@include('layouts.partials.head')
<body>
    @include('layouts.partials.header')
    @yield('banner')
    @yield('content')
    @yield('sale')
</body>
@include('layouts.partials.footer')
</html>
@include('layouts.partials.script')
</html>
